"""Reading a finished experiment: which runs it is, and what can be measured on them.

Nothing here trains the model or needs a GPU. The nine runs left their representations
and predictions behind, and every question the study asks of them afterwards is asked
from a laptop, through this package.
"""

from .experiment import (
    ARMS,
    CHECKPOINT_NAME,
    MODEL,
    SEEDS,
    TIMESTAMP,
    Arm,
    Weights,
    analysis_path,
    checkpoint_path,
    constrained_layer,
    eval_report,
    predictions,
    reported_accuracy,
    representations,
    require_checkpoints,
    run_config,
    run_id,
    training_batches,
    training_duration,
    weights,
)
from .probing import (
    FORMAT_FEATURES,
    MIN_COUNT,
    SPLIT_SEED,
    TRAIN_FRAC,
    classify,
    fit_linear,
    format_matrix,
    keep_frequent,
    majority_floor,
    probe_accuracy,
    residualize,
    scorable,
    split_mask,
    splitter,
    surface_matrices,
    surface_vocabularies,
)
from .statistics import (
    CONFIDENCE,
    PairedDifference,
    Summary,
    paired_difference,
    summarize,
    t_critical,
)
from .subspaces import (
    CONTROL_DRAWS,
    WHERE,
    answer_token_rows,
    delta,
    gain,
    inside,
    output_basis,
    outside,
    random_bases,
    reported_gain,
    scores,
    seed_deltas,
    summarize_places,
)

__all__ = [
    "ARMS",
    "CHECKPOINT_NAME",
    "CONFIDENCE",
    "CONTROL_DRAWS",
    "FORMAT_FEATURES",
    "MIN_COUNT",
    "MODEL",
    "SEEDS",
    "SPLIT_SEED",
    "TIMESTAMP",
    "TRAIN_FRAC",
    "WHERE",
    "Arm",
    "PairedDifference",
    "Summary",
    "Weights",
    "analysis_path",
    "answer_token_rows",
    "checkpoint_path",
    "classify",
    "constrained_layer",
    "delta",
    "eval_report",
    "fit_linear",
    "format_matrix",
    "gain",
    "inside",
    "keep_frequent",
    "majority_floor",
    "output_basis",
    "outside",
    "paired_difference",
    "predictions",
    "probe_accuracy",
    "random_bases",
    "reported_accuracy",
    "reported_gain",
    "representations",
    "require_checkpoints",
    "residualize",
    "run_config",
    "run_id",
    "scorable",
    "scores",
    "seed_deltas",
    "split_mask",
    "splitter",
    "summarize",
    "summarize_places",
    "surface_matrices",
    "surface_vocabularies",
    "t_critical",
    "training_batches",
    "training_duration",
    "weights",
]
